name: Release

on:
  push:
    # Trigger on any tag
    tags: [ '*' ]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm version ${{ github.ref_name }} --no-git-tag-version
      - run: pnpm build
      - run: pnpm publish --access public --no-git-checks
